### ISSUE TITLE
Support GithubActions logs

### ISSUE THREAD

**Issue by staabm** [OctoLinker/OctoLinker#1098]
**Describe the feature**
wouldn't it make sense/be consistent when OctoLinker would link the github-action names from within a github Action log

**Demo**
https://github.com/OctoLinker/OctoLinker/runs/1282733263

examples:

![grafik](https://user-images.githubusercontent.com/120441/96991026-2810d900-1528-11eb-8997-6369a91037ca.png)

**Comment by stefanbuck** [comment]
Sure, it would be awesome if OctoLinker — Links together, what belongs together, but I wonder how much value this adds. Also, from a technical point of view this is not trivial to implement at all. In the past OctoLinker was facing serious performance issues when parsing such large pages. I'll leave this open to collect feedback, but I don't think we will add this any time soon. 

@xt0rted what are your thoughts on this?

**Comment by xt0rted** [comment]
I'd love to have some links to the source repos, I've wanted that myself while looking through the logs, but I'm not sure it's worth trying to add in due to the complexity and how different it'll be from the rest of the plugins.

I contacted support about this since I've wanted it for awhile too. Maybe it could become built-in 🤞 

These are the mockups I included:

<img width="610" alt="Capture" src="https://user-images.githubusercontent.com/831974/97119630-e9c21800-16e7-11eb-93aa-f64c3eabd4ea.png">

<img width="616" alt="Capture2" src="https://user-images.githubusercontent.com/831974/97119633-f0508f80-16e7-11eb-8cac-7bbc2f0a9f48.png">

**Comment by stefanbuck** [comment]
I'm going to close this since it feels out of scope for this project, but would be nice to have (nativily) though.
