### ISSUE TITLE
Show status bar

### ISSUE THREAD

**Issue by tim-phillips** [OctoLinker/OctoLinker#277]
Chrome Version 56.0.2924.87 (64-bit)
OctoLinker latest

OctoLinker should show browser status bar when mousing over a link

**Comment by stefanbuck** [comment]
That's not possible, unfortunately. We don't know the target URL while rendering the links. The process to find the target URL is in many cases request heavy and therefore we can't do this for every link by default on extension start. The actual click on a link will kick off the process.

**Comment by stefanbuck** [comment]
@babenzele is this a big issue for you and if so why? Is this a trust thing?

**Comment by babenzele** [comment]
@stefanbuck Gotcha re: lazy loading the resource. 

It's not a trust thing. I was curious about where some imports were coming from and thought it could be handy to hover over the import to see the url, mostly to see the github org/user the repo is located, without having to click through.

**Comment by josephfrazier** [comment]
Hmm, it might not be hard to add a `mouseover` listener that starts the URL resolution process and shows the results in a tooltip (which there is already code for).

@babenzele, if you're curious, there's some more discussion of making the links into actual `<a href>` elements in https://github.com/OctoLinker/browser-extension/pull/87 and https://github.com/OctoLinker/browser-extension/issues/49#issuecomment-137948995

**Comment by derimagia** [comment]
Just to throw my opinion on it, this is a pretty major UX issue in my opinion. There's at least https://fiatjaf.alhur.es/module-linker/ which seems to improve this quite a lot, but it seems silly to have 2 plugins doing the same thing. 

I can't say I know much about how octolinker works so I can't comment too much on this besides what i have at the moment.

**Comment by stefanbuck** [comment]
I discovered module-linker a few weeks ago and was looking how they do linking. As assumed it prefetches all links on startup which is the major difference between OctoLinker and module-linker. 

@josephfrazier suggested the same technic a while ago, but I wasn't confidence. Mainly because I was afraid to put that many unnecessary traffic on our service, github and all the registries. In worse case one of them would ban our service. Maybe worth to revisit and investigate into it. 

Another major difference is that OctoLinker tries to work specification confirm. For example in NodeJs a require statement can be resolved to many different paths depending on the project structure. `require('../foo)` can be either `../foo.js` or `../foo/index.js`. See [NodeJS reference](https://nodejs.org/api/modules.html#modules_all_together) for more details. We solve such links as soon as the user requests them. OctoLinker performs some HEAD requests for all the possible locations. Doing that by default for every link would increase significant the traffic produced by OctoLinker, not sure what the consequences would be. 

According to the installation count of module-linker, looks like an issue for quite a lot users. I'll investigate into it. Maybe @fiatjaf is willing to help.

Thanks @derimagia for raising attention to this issue on more time.

**Comment by derimagia** [comment]
For the second part, we could do what OctoTree does and accept a token to just get the files in the repo, so its only a single request. Are there other cases where this wouldn't help?

**Comment by stefanbuck** [comment]
I didn't think about that! Good idea and we already have this functionality in place for Sass, Less and Haskell.

**Comment by josephfrazier** [comment]
> For the second part, we could do what OctoTree does and accept a token to just get the files in the repo, so its only a single request. Are there other cases where this wouldn't help?

Maybe a good way to start on this would be to refactor [fetch](https://github.com/OctoLinker/browser-extension/blob/7a12c2665ba5d5999d6cb4786449eef996d33b91/lib/utils/fetch.js) to know which repo its in, use the GitHub API to get a list of files as described [here](https://developer.github.com/v3/git/trees/#get-a-tree-recursively), then handle urls in the repo by checking them against the file list, rather than doing a HEAD request.

**Comment by stefanbuck** [comment]
One of my goals for 2018 is to close (implement a fix) for this issue. I have some rough ideas how to do this. @josephfrazier I'll write down a few lines soon so we can discuss it in detail.

**Comment by stefanbuck** [comment]
Hey @babenzele and @derimagia, are you still interested in such a behaviour? I was working on a proof of concept version which is using real `<a>`-Tags for all links. So far it works, but I would like to verify a few performance concerns and in order to do this I need traffic and your help.

All you have to do is installing [this version](https://github.com/OctoLinker/browser-extension/files/1617736/octolinker-real-links.zip ) and use it (like you hopefully still do 😉). Please disable the other OctoLinker version first before installing. To install this version go to (chrome://extensions/)[chrome://extensions/] and drag and drop the content of the zip into this window. 

The extension uses [Mixpanel](https://mixpanel.com/) to track the performance when pre-fetching the links. It sends the ratio of failing / successfully loaded urls (not the urls itself) and the plugin name. E.g. `2_15 JavaScript`. This helps me to identify bottlenecks so I can improve the code. I'm happy to share the Mixpanel project with you in case you're interested. Just DM me on twitter [@buckstefan](https://twitter.com/buckstefan)

If you have any questions, please let me know.

The source code is available at https://github.com/stefanbuck/browser-extension/tree/real-links

**Comment by babenzele** [comment]
I’ll start using that version this week! Looking forward to it

**Comment by sloria** [comment]
Would love to see this land. I'm currently using Module Linker because it supports real links, but I would switch to Octolinker if this were added.

Thanks @stefanbuck for working on this. Unfortunately, I cannot test your version on Firefox (my primary browser) because Firefox requires add-ons to be [signed](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox). I tried it briefly on Chrome and it works like charm.

**Comment by stefanbuck** [comment]
Over the last few months, I did a lot major refactoring which is required before shipping this feature. I have to admit, that there wasn't much progress on this recently. Also I'm still worried about sending to many requests to GitHub. I think a proper caching strategy should help to avoid requesting the same resource over and over again. However, I'm on it :wink:

**Comment by stefanbuck** [comment]
@tim-phillips @sloria @derimagia Good news, I just finished the last major PR for this feature. It required quite some changes and therefore I would like to run a beta phase of the upcoming version. If you want to participate in beta, join us on [spectrum](https://spectrum.chat/octolinker/v5/join/77a0134c-1147-4e85-900c-db42875a8a98) for more details.

**Comment by stefanbuck** [comment]
This will be fixed in the next major release which is scheduled for end of April. In case you don't want to wait, a beta version is available here https://github.com/OctoLinker/OctoLinker/issues/549
