### ISSUE TITLE
Chrome extension asking for new permissions to octolinker.now.sh

### ISSUE THREAD

**Issue by natew** [OctoLinker/OctoLinker#558]
Just wanted to get clarification on this, especially write access?

**Comment by stefanbuck** [comment]
Thanks for asking this important quesiton. I didn't covered this in the changelog, but I'll add a note there as well. 

In an early version of OctoLinker, we shipped a giant mapping list of all npm packages and their related GitHub project url as part of the extension. This worked well until npm reached a critical mass. We aslo started supporting other languages so this wasn’t approachable anymore. 

Since a few years, all external dependencies are resolved through our OctoLinker API. It’s basically a reverse proxy with caching. Until now this API was deployed on Heroku https://githublinker.herokuapp.com/ (GitHubLinker was the previous name). With v5 we use ZEIT now and therfore the URL changed to https://octolinker-api.now.sh

Regarding the write access. The browser extension API doesn't allow to break permissons further down. I tried to restrict permissions as possible, but the listed domains are the required minimum in order to make OctoLinker work. 

Does this anwers your question? Please let me know if something is still not clear.

**Comment by stefanbuck** [comment]
The new version is out for quite some time so I assume it's time to close this issue
