### ISSUE TITLE
[Question] CSS clash with refined-github

### ISSUE THREAD

**Issue by sidvishnoi** [OctoLinker/OctoLinker#639]
Hi,
We're working on a feature in [sindresorhus/refined-github](https://github.com/sindresorhus/refined-github). We found a `.highlight` in [helper-insert-link/style.css](https://github.com/OctoLinker/OctoLinker/blob/0174f49ed52e936dadcacc81f8cdf428d86bc950/packages/helper-insert-link/style.css#L45-L47) having `position: relative`. This selector gets applied to `.file > .data.js-blob-wrapper` on files tab of a PR, breaking the feature we're working upon.

That position relative is conflicting with a piece of our CSS as described at https://github.com/sindresorhus/refined-github/pull/2320#issuecomment-520472822.

Question: What is the purpose of this `.highlight`? Can it be removed from PR files diff and PR commit page? Or can its selector be changed so it doesn't apply to `.file`? 

(Sorry for not following issue template.)

**Comment by stefanbuck** [comment]
Hi, thanks for reaching out! This is just needed for code snippets which can appear in issues, comment and markdown files. The latter is most likely preventing the removal of this position relative since it's also within a blob `.files` selector. Without position relative the pink dot is not aligned with the code snippets (see screenshots below). If you know a better way I'm happy to remove the position relative 

## With position relative
![image](https://user-images.githubusercontent.com/1393946/62885053-323a2380-bd38-11e9-861a-d859fb7d762d.png)

## Without position relative
![image](https://user-images.githubusercontent.com/1393946/62885011-1df62680-bd38-11e9-9fa8-7cfc7bae26b7.png)

**Comment by fregante** [comment]
If it’s only required there, I think that the selector can be `.markdown_body .highlight` or something like that
