### ISSUE TITLE
Doesnt work when there is hyphen in github username/reponame (golang)

### ISSUE THREAD

**Issue by manoj398** [OctoLinker/OctoLinker#642]
Doesnt work when username/reponame has hyphens in github. In golang all the import paths are absolute. So for github imports we need to take care of all the characters that can be allowed in username and reponame. 

**Reproduction**
It can be verified in https://github.com/ethereum/go-ethereum repo. 

**Intended**
It should work as normal github urls (like its currently working when there are no special characters)

**Comment by stefanbuck** [comment]
Thanks for reporting this issue. I found out that this issue isn't related to the hyphen itself. The domain github.com is the issue since OctoLinker tries to resolve https://github.com/ethereum/go-ethereum/core/types rather than https://github.com/ethereum/go-ethereum/tree/master/core/types

I'm currently working on a fix

**Comment by stefanbuck** [comment]
Fix https://github.com/OctoLinker/OctoLinker/pull/650

**Comment by stefanbuck** [comment]
Will release a fix either later today or tomorrow.
