### ISSUE TITLE
support gh api token via firefox sync

### ISSUE THREAD

**Issue by staabm** [OctoLinker/OctoLinker#848]
recently I had to setup a new device and used firefox sync to get all my extensions and browsing history/settings etc. across.

I was wondering, why I had to re-enter the github api access token again while https://github.com/sindresorhus/refined-github managed to sync the token with the firefox profile.

maybe thats a use case which could be supported?

**Comment by staabm** [comment]
Per https://github.com/fregante/github-issue-link-status/issues/25#issuecomment-600557613 there is a single setting for that.. not sure you use it right now

**Comment by stefanbuck** [comment]
OctoLinker was using the sync API in the past, but this functionality got removed from OctoLinker last year. The sync store API isn’t meant for confidential data since the data are not encrypted so I thought its better to remove it. See https://github.com/OctoLinker/OctoLinker/pull/544

So far nobody complained about it. Let me know what you

**Comment by staabm** [comment]
I see, makes sense
